package com.ecat.core.Device;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ScheduledExecutorService;

import lombok.Getter;
import lombok.Setter;

import com.ecat.core.EcatCore;
import com.ecat.core.I18n.I18nProxy;
import com.ecat.core.I18n.I18nHelper;
import com.ecat.core.I18n.I18nKeyPath;
import com.ecat.core.Integration.IntegrationBase;
import com.ecat.core.State.AttributeBase;
import com.ecat.core.Utils.LogFactory;
import com.ecat.core.Utils.Log;

/**
 * 设备基类，所有设备必须继承该类
 * 负责设备的基本信息、属性管理、状态更新等功能
 * 设备具体的通信和控制逻辑由子类实现
 * 
 * @apiNote name i18n supported, path: devices.{typeName}.{property}, typeName is auto generated by class name
 * @apiNote property: name, vendor, model
 * 
 * @implSpec 继承该类需要实现init、start、stop、release方法，完成设备的初始化、启动、停止和资源释放逻辑
 * 
 * @author coffee
 */

public abstract class DeviceBase implements DeviceControl {
    @Getter
    protected EcatCore core;
    protected Map<String, Object> config;
    @Getter
    @Setter
    protected IntegrationBase integration;
    protected Log log;

    // id: mockserial-001 # 设备ID，Core管理，必填，全core不可重复，设备区分使用，建议使用ip或mac或sn等唯一标识
    // name: 测试串口设备1 # 设备名称，Core管理，必填，前端显示
    // class: air.monitor.pm # 所属ecat设备类型，Core管理，选填，前端默认样式，见DeviceClasses的className
    // sn: XH2000E-001 # 设备序列号，Core管理，选填，前端显示
    // vendor: 先河环保 # 设备厂商，Core管理，选填，前端显示
    // model: XH2000E # 设备型号，Core管理，选填，前端显示
    //abilities: # 设备能力，Core管理，选填
    //   - gas.switch
    //   - gas.zero.generate
    //   - gas.span.generate

    @Getter
    protected String id; // device id
    @Getter
    protected String name;
    @Getter
    protected String sn;
    @Getter
    protected String vendor;
    @Getter
    protected String model;
    @Getter
    protected DeviceClasses deviceClass;
    @Getter
    protected DeviceStatus deviceStatus;
    @Getter
    private List<DeviceAbility> abilities;
    
    private Map<String, AttributeBase<?>> attrs;

    protected final I18nProxy i18n = I18nHelper.createProxy(this.getClass());


    public DeviceBase(Map<String, Object> config) {
        this.log = LogFactory.getLogger(getClass());

        this.config = config;
        this.id = (String) config.get("id");
        this.name = (String) config.get("name");
        
        // sn is optional , if config not has sn set sn = null
        this.deviceClass = DeviceClasses.getEnum((String) config.getOrDefault("class", null));
        this.deviceStatus = DeviceStatus.UNKNOWN;
        this.abilities = new ArrayList<>();
        List<String> abilities = (List<String> ) config.getOrDefault("abilities", null);
        if(abilities != null){
            for (String ability : abilities) {
                this.abilities.add(DeviceAbility.getEnum(ability));
            }
        }
        
        this.sn = (String) config.getOrDefault("sn", null);
        this.vendor = (String) config.getOrDefault("vendor", null);
        this.model = (String) config.getOrDefault("model", null);

        this.attrs = new HashMap<>();
    }

    public void load(EcatCore core) {
        this.core = core;
    }

    /**
     * 获取设备的定时任务执行器
     * 
     */
    public ScheduledExecutorService getScheduledExecutor() {
        return this.core.getTaskManager().getExecutorService();
    }

    /**
     * 设置设备的配置信息，完成属性与设备的绑定
     * 
     * @param attr 需要设置的属性
     * 
     */
    public boolean setAttribute(AttributeBase<?> attr) {
        if (attr == null) {
            return false;
        }
        attr.setDevice(this); // 绑定属性与设备的关系以及使用device所在集成的i18n资源
        attrs.put(attr.getAttrID(), attr);
        return true;
    }

    public Map<String, AttributeBase<?>> getAttrs() {
        return attrs;
    }

    /**
     * 更新设备属性状态，提交给bus
     * 按需更新，只有属性值发生变化时才更新
     */
    public boolean publicAttrsState() {
        try{
            for (AttributeBase<?> attribute : attrs.values()) {
                attribute.publicState();
            }
        }
        catch (Exception e){
            log.error(I18nHelper.t("error.failed_to_update_state"), e);
            return false;
        }
        return true;
    }

    /**
     * 接收设备的原始数据，用于integration统一收到数据后向device分发处理
     *
     * @param binaryArray 原始数据
     *
     */
    public void receiveRawData(byte[] binaryArray) {
        throw new UnsupportedOperationException("Not implemented");
    }

    /**
     * 获取设备类型名称，用于国际化分组
     * 默认实现基于类名自动生成，子类可以覆盖以提供自定义名称
     * 例如：
     * WeatherSensor -> weather_sensor
     * CODevice -> codevice
     * RACC2Device -> racc2device
     * Air5030iDevice -> air5030i_device
     *
     * @return 设备类型名称，小写格式
     */
    public String getTypeName() {
        String className = getClass().getSimpleName();
        // 将驼峰命名转换为下划线分隔的小写名称
        return className.replaceAll("([a-z])([A-Z]+)", "$1_$2").toLowerCase();
    }

    /**
     * 获取设备的国际化前缀路径
     * 用于按设备分组国际化资源
     *
     * @return I18nKeyPath 设备分组路径前缀，格式为 "devices.{deviceClassNameLowerCase}"
     */
    public I18nKeyPath getI18nPrefix() {
        String typeName = getTypeName();
        if (typeName != null && !typeName.isEmpty()) {
            return new I18nKeyPath("devices." + typeName + ".", "");
        } else {
            return null;
        }
    }

}
