/*
 * Copyright (c) 2026 ECAT Team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ecat.core.Device;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.atomic.AtomicLong;

import lombok.Getter;
import lombok.Setter;

import com.ecat.core.ConfigEntry.ConfigEntry;
import com.ecat.core.EcatCore;
import com.ecat.core.I18n.I18nProxy;
import com.ecat.core.I18n.I18nHelper;
import com.ecat.core.I18n.I18nKeyPath;
import com.ecat.core.Integration.IntegrationBase;
import com.ecat.core.State.AttributeBase;
import com.ecat.core.State.AttributeStatus;
import com.ecat.core.Utils.LogFactory;
import com.ecat.core.Utils.Log;

/**
 * 设备基类，所有设备必须继承该类
 * 负责设备的基本信息、属性管理、状态更新等功能
 * 设备具体的通信和控制逻辑由子类实现
 * 
 * @apiNote name i18n supported, path: devices.{typeName}.{property}, typeName is auto generated by class name
 * @apiNote property: name, vendor, model
 * 
 * @implSpec 继承该类需要实现init、start、stop、release方法，完成设备的初始化、启动、停止和资源释放逻辑
 * 
 * @author coffee
 */

public abstract class DeviceBase implements DeviceControl {
    @Getter
    protected EcatCore core;
    protected Map<String, Object> config;
    @Getter
    @Setter
    protected IntegrationBase integration;
    protected Log log;

    // id: mockserial-001 # 设备ID，Core管理，必填，全core不可重复，设备区分使用，建议使用ip或mac或sn等唯一标识
    // name: 测试串口设备1 # 设备名称，Core管理，必填，前端显示
    // class: air.monitor.pm # 所属ecat设备类型，Core管理，选填，前端默认样式，见DeviceClasses的className
    // sn: XH2000E-001 # 设备序列号，Core管理，选填，前端显示
    // vendor: 先河环保 # 设备厂商，Core管理，选填，前端显示
    // model: XH2000E # 设备型号，Core管理，选填，前端显示
    //abilities: # 设备能力，Core管理，选填
    //   - gas.switch
    //   - gas.zero.generate
    //   - gas.span.generate

    @Deprecated
    protected String id = null; // 旧yml中device id， 使用config flow后改用entry.getEntryId()，旧可删除此字段

    @Getter
    protected ConfigEntry entry; // 配置条目引用，与设备一对一关系
    @Getter
    protected String name;
    @Getter
    protected String sn;
    @Getter
    protected String vendor;
    @Getter
    protected String model;
    @Getter
    protected DeviceClasses deviceClass;
    protected DeviceStatus deviceStatus;

    /**
     * 获取设备状态。
     *
     * <p>采用懒计算机制：每次调用时通过 {@link #computeDeviceStatus()} 重新计算。
     * 子类可覆写 {@code computeDeviceStatus()} 实现自定义状态聚合逻辑。
     *
     * <p>如果子类自行管理 deviceStatus 字段（如直接赋值），可覆写此方法直接返回 {@code this.deviceStatus}，
     * 跳过计算逻辑，保持向后兼容。
     *
     * @return 当前设备状态
     */
    public DeviceStatus getDeviceStatus() {
        DeviceStatus computed = computeDeviceStatus();
        if (computed != null) {
            this.deviceStatus = computed;
        }
        return this.deviceStatus;
    }

    /**
     * 从属性状态懒计算设备状态（通用算法）。
     *
     * <p>通用计算逻辑（按优先级）：
     * <ol>
     *   <li><b>最严重的属性状态</b>：遍历所有属性，找到最严重的 AttributeStatus，映射为 DeviceStatus</li>
     *   <li><b>在线判断</b>：如果有属性在近期更新过（60秒内），视为 NORMAL</li>
     *   <li><b>离线/未知</b>：无任何数据更新 → UNKNOWN</li>
     * </ol>
     *
     * <p>子类可覆写此方法实现自定义逻辑。参考：
     * <ul>
     *   <li>{@code MyDeviceBase.computeDeviceStatus()} — sailhero manual_status 优先</li>
     *   <li>{@code LogicDevice.computeDeviceStatus()} — 逻辑设备状态属性聚合</li>
     * </ul>
     *
     * @return 计算得到的设备状态，返回 null 表示不更新字段
     */
    protected DeviceStatus computeDeviceStatus() {
        if (getAttrs() == null || getAttrs().isEmpty()) {
            return DeviceStatus.UNKNOWN;
        }

        // Priority 1: 扫描所有属性，找到最严重的 AttributeStatus
        DeviceStatus worstFromAttrs = scanWorstAttributeStatus();
        if (worstFromAttrs != null && worstFromAttrs != DeviceStatus.UNKNOWN) {
            return worstFromAttrs;
        }

        // Priority 2: 在线判断 — 有近期更新数据则为 NORMAL
        if (hasRecentUpdate()) {
            return DeviceStatus.NORMAL;
        }

        // Priority 3: 无数据或数据过期
        return DeviceStatus.UNKNOWN;
    }

    /**
     * 扫描所有属性，找到最严重的 AttributeStatus 并映射为 DeviceStatus。
     *
     * @return 最严重的 DeviceStatus，如果所有属性都是 NORMAL 或无状态则返回 null
     */
    private DeviceStatus scanWorstAttributeStatus() {
        DeviceStatus worst = null;
        for (AttributeBase<?> attr : getAttrs().values()) {
            AttributeStatus attrStatus = attr.getStatus();
            if (attrStatus != null && attrStatus != AttributeStatus.EMPTY) {
                DeviceStatus ds = mapAttributeStatusToDeviceStatus(attrStatus);
                if (ds != null) {
                    int severity = getStatusSeverity(ds);
                    int currentWorst = (worst != null) ? getStatusSeverity(worst) : 0;
                    if (severity > currentWorst) {
                        worst = ds;
                    }
                }
            }
        }
        return worst;
    }

    /**
     * 检查是否有属性在最近 60 秒内更新过。
     *
     * @return true 如果至少有一个属性的 updateTime 在 60 秒内
     */
    private boolean hasRecentUpdate() {
        java.time.LocalDateTime cutoff = java.time.LocalDateTime.now().minusSeconds(60);
        for (AttributeBase<?> attr : getAttrs().values()) {
            java.time.LocalDateTime ut = attr.getUpdateTime();
            if (ut != null && ut.isAfter(cutoff)) {
                return true;
            }
        }
        return false;
    }

    /**
     * 设备状态严重程度排序。
     * ALARM(4) > MAINTENANCE(3) = CALIBRATION(3) > WARM_UP(2) = DIAGNOSTIC(2) = RECOVERY(2) > NORMAL(1) = MEASURE(1) > UNKNOWN(0)
     */
    private int getStatusSeverity(DeviceStatus ds) {
        if (ds == null) return 0;
        switch (ds) {
            case ALARM: return 4;
            case MAINTENANCE: return 3;
            case CALIBRATION: return 3;
            case WARM_UP: return 2;
            case DIAGNOSTIC: return 2;
            case RECOVERY: return 2;
            case NORMAL: return 1;
            case MEASURE: return 1;
            default: return 0; // UNKNOWN, STANDBY
        }
    }

    /**
     * 将 AttributeStatus 映射为 DeviceStatus（通用映射）。
     *
     * <p>分组规则：
     * <ul>
     *   <li>NORMAL → NORMAL</li>
     *   <li>ALARM, MALFUNCTION → ALARM</li>
     *   <li>CALIBRATION 系列 → CALIBRATION</li>
     *   <li>MAINTENANCE, DEVICE_REPLACEMENT → MAINTENANCE</li>
     *   <li>WAITING → WARM_UP</li>
     *   <li>统计类状态 → DIAGNOSTIC</li>
     *   <li>EMPTY, OTHER, 未知 → UNKNOWN</li>
     * </ul>
     */
    protected DeviceStatus mapAttributeStatusToDeviceStatus(AttributeStatus attrStatus) {
        if (attrStatus == null || attrStatus == AttributeStatus.EMPTY) {
            return DeviceStatus.UNKNOWN;
        }
        switch (attrStatus) {
            case NORMAL:
                return DeviceStatus.NORMAL;
            case ALARM:
            case MALFUNCTION:
                return DeviceStatus.ALARM;
            case CALIBRATION:
            case ZERO_CALIBRATION:
            case SPAN_CALIBRATION:
            case ZERO_CHECK:
            case SPAN_CHECK:
            case ACCURACY_CHECK:
            case FLOW_CHECK:
            case QUALITY_CHECK:
            case ZERO_DRIFT:
            case SPAN_DRIFT:
            case SPAN_REPRODUCIBILITY:
            case MULTI_POINT_SPAN:
            case PRECISION_CHECK:
            case TEMP_PRESSURE_CALIBRATION:
                return DeviceStatus.CALIBRATION;
            case MAINTENANCE:
            case DEVICE_REPLACEMENT:
                return DeviceStatus.MAINTENANCE;
            case WAITING:
                return DeviceStatus.WARM_UP;
            case INSUFFICIENT:
            case ABNORMAL_CHANGE:
            case NO_CHANGE:
            case OVER_UPPER_LIMIT:
            case UNDER_LOWER_LIMIT:
                return DeviceStatus.DIAGNOSTIC;
            default:
                return DeviceStatus.UNKNOWN;
        }
    }
    @Getter
    private List<DeviceAbility> abilities;
    
    /**
     * 物理测点映射表，物理测点ID -> 属性
     */
    private Map<String, AttributeBase<?>> attrs;

    // 原子类保证多线程安全的自增ID生成器
    private static final AtomicLong OBJECT_ID_GENERATOR = new AtomicLong(1);
    // 每个设备对象的全局唯一ID
    @Getter
    private final long objectId;

    protected final I18nProxy i18n = I18nHelper.createProxy(this.getClass());


    /**
     * 从 ConfigEntry 构建设备（推荐）
     * 自动从 entry 中提取 uniqueId 作为 deviceId，保存 entry 引用建立一对一关系
     *
     * @param entry 配置条目
     */
    public DeviceBase(ConfigEntry entry) {
        this.log = LogFactory.getLogger(getClass());
        this.objectId = OBJECT_ID_GENERATOR.getAndIncrement();
        this.entry = entry;
        this.config = entry.getData();
        initDevice(entry.getData());
    }

    /**
     * 从 config Map 构建设备（旧式，已废弃）
     *
     * @param config 设备配置
     * @deprecated 使用 {@link #DeviceBase(ConfigEntry)} 替代
     */
    @Deprecated
    public DeviceBase(Map<String, Object> config) {
        this.log = LogFactory.getLogger(getClass());
        this.objectId = OBJECT_ID_GENERATOR.getAndIncrement();
        this.config = config;
        this.entry = new ConfigEntry(); // create empty config entry temporary
        this.id = (String) config.get("id");
        initDevice(config);
    }

    private void initDevice(Map<String, Object> config) {
        this.name = (String) config.get("name");

        // sn is optional , if config not has sn set sn = null
        this.deviceClass = DeviceClasses.getEnum((String) config.getOrDefault("class", null));
        this.deviceStatus = DeviceStatus.UNKNOWN;
        this.abilities = new ArrayList<>();
        List<String> abilities = (List<String> ) config.getOrDefault("abilities", null);
        if(abilities != null){
            for (String ability : abilities) {
                this.abilities.add(DeviceAbility.getEnum(ability));
            }
        }

        this.sn = (String) config.getOrDefault("sn", null);
        this.vendor = (String) config.getOrDefault("vendor", null);
        this.model = (String) config.getOrDefault("model", null);

        this.attrs = new HashMap<>();
    }

    public void load(EcatCore core) {
        this.core = core;
    }

    /**
     * 获取设备的id标识符
     * 全局唯一
     * 全局不会更改，除非entry被删除
     * 可作为数据库或关联的ID，确保能找到这个配置
     * 但是因为不同集成的reconfigure entry flow不严谨导致设备类型发生变化，可能存在id没变但是设备类型发生变化
     * 因此如果业务方要求强一致应当监听core的 on reconfigured 的事件自行判断
     * 
     * @return 兼容 旧构建函数方式，后面当旧构建函数删除后可改为返回 entry.getEntryId()
     */
    public String getId(){
        return id == null ? entry.getEntryId() : id;
    }

    /**
     * 获取设备的唯一业务标识符，具有业务含义的
     * 全局唯一
     * 可能会修改：当用户reconfigure entry后部分支持同类型多设备的集成的entry极大可能变化，比如SN修改会发生改变，只能作为业务展示
     * @return
     */
    public String getUniqueId(){
        return entry.getUniqueId();
    }

    /**
     * 获取设备的定时任务执行器
     * 
     */
    public ScheduledExecutorService getScheduledExecutor() {
        return this.core.getTaskManager().getExecutorService();
    }

    /**
     * 设置设备的配置信息，完成属性与设备的绑定
     * 
     * @param attr 需要设置的属性
     * 
     */
    public boolean setAttribute(AttributeBase<?> attr) {
        if (attr == null) {
            return false;
        }
        attr.setDevice(this); // 绑定属性与设备的关系以及使用device所在集成的i18n资源
        attrs.put(attr.getAttributeID(), attr);
        return true;
    }

    public Map<String, AttributeBase<?>> getAttrs() {
        return attrs;
    }

    /**
     * 更新设备属性状态，提交给bus
     * 按需更新，只有属性值发生变化时才更新
     */
    public boolean publicAttrsState() {
        try{
            for (AttributeBase<?> attribute : attrs.values()) {
                attribute.publicState();
            }
        }
        catch (Exception e){
            log.error(I18nHelper.t("error.failed_to_update_state"), e);
            return false;
        }
        return true;
    }

    /**
     * 接收设备的原始数据，用于integration统一收到数据后向device分发处理
     *
     * @param binaryArray 原始数据
     *
     */
    public void receiveRawData(byte[] binaryArray) {
        throw new UnsupportedOperationException("Not implemented");
    }

    /**
     * 获取设备类型名称，用于国际化分组
     * 默认实现基于类名自动生成，子类可以覆盖以提供自定义名称
     * 例如：
     * WeatherSensor -> weather_sensor
     * CODevice -> codevice
     * RACC2Device -> racc2device
     * Air5030iDevice -> air5030i_device
     *
     * @return 设备类型名称，小写格式
     */
    public String getTypeName() {
        String className = getClass().getSimpleName();
        // 将驼峰命名转换为下划线分隔的小写名称
        return className.replaceAll("([a-z])([A-Z]+)", "$1_$2").toLowerCase();
    }

    /**
     * 获取设备的国际化前缀路径
     * 用于按设备分组国际化资源
     *
     * @return I18nKeyPath 设备分组路径前缀，格式为 "devices.{deviceClassNameLowerCase}"
     */
    public I18nKeyPath getI18nPrefix() {
        String typeName = getTypeName();
        if (typeName != null && !typeName.isEmpty()) {
            return new I18nKeyPath("devices." + typeName + ".", "");
        } else {
            return null;
        }
    }

}
