/*
 * Copyright (c) 2026 ECAT Team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ecat.core.Device;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.atomic.AtomicLong;

import lombok.Getter;
import lombok.Setter;

import com.ecat.core.ConfigEntry.ConfigEntry;
import com.ecat.core.EcatCore;
import com.ecat.core.I18n.I18nProxy;
import com.ecat.core.I18n.I18nHelper;
import com.ecat.core.I18n.I18nKeyPath;
import com.ecat.core.Integration.IntegrationBase;
import com.ecat.core.State.AttrState;
import com.ecat.core.State.AttributeBase;
import com.ecat.core.State.AttributeStatus;
import com.ecat.core.Utils.LogFactory;
import com.ecat.core.Utils.Log;

/**
 * 设备基类，所有设备必须继承该类
 * 负责设备的基本信息、属性管理、状态更新等功能
 * 设备具体的通信和控制逻辑由子类实现
 * 
 * @apiNote name i18n supported, path: devices.{typeName}.{property}, typeName is auto generated by class name
 * @apiNote property: name, vendor, model
 * 
 * @implSpec 继承该类需要实现init、start、stop、release方法，完成设备的初始化、启动、停止和资源释放逻辑
 * 
 * @author coffee
 */

public abstract class DeviceBase implements DeviceControl {
    @Getter
    protected EcatCore core;
    protected Map<String, Object> config;
    @Getter
    @Setter
    protected IntegrationBase integration;
    protected Log log;

    // id: mockserial-001 # 设备ID，Core管理，必填，全core不可重复，设备区分使用，建议使用ip或mac或sn等唯一标识
    // name: 测试串口设备1 # 设备名称，Core管理，必填，前端显示
    // class: air.monitor.pm # 所属ecat设备类型，Core管理，选填，前端默认样式，见DeviceClasses的className
    // sn: XH2000E-001 # 设备序列号，Core管理，选填，前端显示
    // vendor: 先河环保 # 设备厂商，Core管理，选填，前端显示
    // model: XH2000E # 设备型号，Core管理，选填，前端显示
    //abilities: # 设备能力，Core管理，选填
    //   - gas.switch
    //   - gas.zero.generate
    //   - gas.span.generate

    /**
     * 设备主键 id：core 在构造函数铸造的稳定 UUID。跨重启经 DeviceRegistry.getOrCreate 用持久化值覆盖。
     * 替代旧的"entryId 兼当 deviceId"折叠；entryId 退回 ConfigEntry 自身主键。
     * setId 包级私有——仅 com.ecat.core.Device（DeviceRegistry.getOrCreate）可改，外部不可变。
     */
    protected String id;

    /**
     * 设备硬件锚点 uniqueId：entry-backed 从 entry.getUniqueId() 取；网关子设备从构造入参取
     * （其 entry 是网关的，entry.getUniqueId() 是网关的而非子设备的）。
     * 仅 coordinate 内唯一，只用于 get-or-create 物理匹配/重复发现去重，不进业务/事件。
     */
    protected String uniqueId;

    @Getter
    protected ConfigEntry entry; // 配置条目引用（entry-backed=自身 entry；网关子设备=网关 entry，1:N back-ref）

    /**
     * 获取设备所属集成的坐标标识（如 com.ecat:integration-hikvision）。
     *
     * <p>委托给 {@link ConfigEntry#getCoordinate()}，子类和外部模块可直接通过设备获取坐标，
     * 无需自行维护或穿透传递 coordinate 参数。
     *
     * @return 集成坐标，entry 未设置时返回 null
     */
    public String getCoordinate() {
        return entry != null ? entry.getCoordinate() : null;
    }
    @Getter
    protected String name;
    @Getter
    protected String sn;
    @Getter
    protected String vendor;
    @Getter
    protected String model;
    @Getter
    protected DeviceClasses deviceClass;
    protected DeviceStatus deviceStatus;

    /**
     * 获取设备状态。
     *
     * <p>采用懒计算机制：每次调用时通过 {@link #computeDeviceStatus()} 重新计算。
     * 子类可覆写 {@code computeDeviceStatus()} 实现自定义状态聚合逻辑。
     *
     * <p>如果子类自行管理 deviceStatus 字段（如直接赋值），可覆写此方法直接返回 {@code this.deviceStatus}，
     * 跳过计算逻辑，保持向后兼容。
     *
     * @return 当前设备状态
     */
    public DeviceStatus getDeviceStatus() {
        DeviceStatus computed = computeDeviceStatus();
        if (computed != null) {
            this.deviceStatus = computed;
        }
        return this.deviceStatus;
    }

    /**
     * 从属性状态懒计算设备状态（通用算法）。
     *
     * <p>通用计算逻辑（按优先级）：
     * <ol>
     *   <li><b>最严重的属性状态</b>：遍历所有属性，找到最严重的 AttributeStatus，映射为 DeviceStatus</li>
     *   <li><b>在线判断</b>：如果有属性在近期更新过（60秒内），视为 NORMAL</li>
     *   <li><b>离线/未知</b>：无任何数据更新 → UNKNOWN</li>
     * </ol>
     *
     * <p>子类可覆写此方法实现自定义逻辑。参考：
     * <ul>
     *   <li>{@code MyDeviceBase.computeDeviceStatus()} — sailhero manual_status 优先</li>
     *   <li>{@code LogicDevice.computeDeviceStatus()} — 逻辑设备状态属性聚合</li>
     * </ul>
     *
     * @return 计算得到的设备状态，返回 null 表示不更新字段
     */
    protected DeviceStatus computeDeviceStatus() {
        if (getAttrs() == null || getAttrs().isEmpty()) {
            return DeviceStatus.UNKNOWN;
        }

        // Priority 1: 扫描所有属性，找到最严重的 AttributeStatus
        DeviceStatus worstFromAttrs = scanWorstAttributeStatus();
        if (worstFromAttrs != null && worstFromAttrs != DeviceStatus.UNKNOWN) {
            return worstFromAttrs;
        }

        // Priority 2: 在线判断 — 有近期更新数据则为 NORMAL
        if (hasRecentUpdate()) {
            return DeviceStatus.NORMAL;
        }

        // Priority 3: 无数据或数据过期
        return DeviceStatus.UNKNOWN;
    }

    /**
     * 扫描所有属性，找到最严重的 AttributeStatus 并映射为 DeviceStatus。
     *
     * @return 最严重的 DeviceStatus，如果所有属性都是 NORMAL 或无状态则返回 null
     */
    private DeviceStatus scanWorstAttributeStatus() {
        DeviceStatus worst = null;
        for (AttributeBase<?> attr : getAttrs().values()) {
            // attr.getStatus() 已降为 protected：跨类经不可变 AttrState 读取。
            // attr.getState() 在属性首次 updateValue 前为 null，按无状态跳过
            // （保持原 getStatus() 返回 EMPTY 时的跳过语义）。
            AttrState<?> attrState = attr.getState();
            AttributeStatus attrStatus = attrState != null ? attrState.getStatus() : null;
            if (attrStatus != null && attrStatus != AttributeStatus.EMPTY) {
                DeviceStatus ds = mapAttributeStatusToDeviceStatus(attrStatus);
                if (ds != null) {
                    int severity = getStatusSeverity(ds);
                    int currentWorst = (worst != null) ? getStatusSeverity(worst) : 0;
                    if (severity > currentWorst) {
                        worst = ds;
                    }
                }
            }
        }
        return worst;
    }

    /**
     * 检查是否有属性在最近 60 秒内更新过。
     *
     * @return true 如果至少有一个属性的 updateTime 在 60 秒内
     */
    private boolean hasRecentUpdate() {
        // updateTime 已统一为 Instant（跨时区）；cutoff 用同一时钟比较。
        java.time.Instant cutoff = java.time.Instant.now().minusSeconds(60);
        for (AttributeBase<?> attr : getAttrs().values()) {
            // 跨类经不可变 AttrState 读 lastUpdated（公开访问，单次 volatile 读防撕裂）。
            // attr.getState() 在属性从未 updateValue 时为 null，按未更新跳过。
            AttrState<?> attrState = attr.getState();
            java.time.Instant ut = attrState != null ? attrState.getLastUpdated() : null;
            if (ut != null && ut.isAfter(cutoff)) {
                return true;
            }
        }
        return false;
    }

    /**
     * 设备状态严重程度排序。
     * ALARM(4) > MAINTENANCE(3) = CALIBRATION(3) > WARM_UP(2) = DIAGNOSTIC(2) = RECOVERY(2) > NORMAL(1) = MEASURE(1) > UNKNOWN(0)
     */
    private int getStatusSeverity(DeviceStatus ds) {
        if (ds == null) return 0;
        switch (ds) {
            case ALARM: return 4;
            case MAINTENANCE: return 3;
            case CALIBRATION: return 3;
            case WARM_UP: return 2;
            case DIAGNOSTIC: return 2;
            case RECOVERY: return 2;
            case NORMAL: return 1;
            case MEASURE: return 1;
            default: return 0; // UNKNOWN, STANDBY
        }
    }

    /**
     * 将 AttributeStatus 映射为 DeviceStatus（通用映射）。
     *
     * <p>分组规则：
     * <ul>
     *   <li>NORMAL → NORMAL</li>
     *   <li>ALARM, MALFUNCTION → ALARM</li>
     *   <li>CALIBRATION 系列 → CALIBRATION</li>
     *   <li>MAINTENANCE, DEVICE_REPLACEMENT → MAINTENANCE</li>
     *   <li>WAITING → WARM_UP</li>
     *   <li>统计类状态 → DIAGNOSTIC</li>
     *   <li>EMPTY, OTHER, 未知 → UNKNOWN</li>
     * </ul>
     */
    protected DeviceStatus mapAttributeStatusToDeviceStatus(AttributeStatus attrStatus) {
        if (attrStatus == null || attrStatus == AttributeStatus.EMPTY) {
            return DeviceStatus.UNKNOWN;
        }
        switch (attrStatus) {
            case NORMAL:
                return DeviceStatus.NORMAL;
            case ALARM:
            case MALFUNCTION:
                return DeviceStatus.ALARM;
            case CALIBRATION:
            case ZERO_CALIBRATION:
            case SPAN_CALIBRATION:
            case ZERO_CHECK:
            case SPAN_CHECK:
            case ACCURACY_CHECK:
            case FLOW_CHECK:
            case QUALITY_CHECK:
            case ZERO_DRIFT:
            case SPAN_DRIFT:
            case SPAN_REPRODUCIBILITY:
            case MULTI_POINT_SPAN:
            case PRECISION_CHECK:
            case TEMP_PRESSURE_CALIBRATION:
                return DeviceStatus.CALIBRATION;
            case MAINTENANCE:
            case DEVICE_REPLACEMENT:
                return DeviceStatus.MAINTENANCE;
            case WAITING:
                return DeviceStatus.WARM_UP;
            case INSUFFICIENT:
            case ABNORMAL_CHANGE:
            case NO_CHANGE:
            case OVER_UPPER_LIMIT:
            case UNDER_LOWER_LIMIT:
                return DeviceStatus.DIAGNOSTIC;
            default:
                return DeviceStatus.UNKNOWN;
        }
    }
    @Getter
    private List<DeviceAbility> abilities;
    
    /**
     * 物理测点映射表，物理测点ID -> 属性
     */
    private Map<String, AttributeBase<?>> attrs;

    // 原子类保证多线程安全的自增ID生成器
    private static final AtomicLong OBJECT_ID_GENERATOR = new AtomicLong(1);
    // 每个设备对象的全局唯一ID
    @Getter
    private final long objectId;

    protected final I18nProxy i18n = I18nHelper.createProxy(this.getClass());


    /**
     * 从 ConfigEntry 构建设备（推荐）。
     *
     * <p>保存 entry 引用建立设备与配置的一对一关系。此时 {@link #getId()} 返回
     * {@code entry.getEntryId()}（系统生成 UUID，设备注册表以此 entryId 为 key），
     * {@link #getUniqueId()} 返回 {@code entry.getUniqueId()}（业务标识，如 厂家_sn）。
     *
     * @param entry 配置条目
     */
    public DeviceBase(ConfigEntry entry) {
        this.log = LogFactory.getLogger(getClass());
        this.objectId = OBJECT_ID_GENERATOR.getAndIncrement();
        this.entry = entry;
        this.config = entry.getData();
        this.id = java.util.UUID.randomUUID().toString();
        this.uniqueId = entry.getUniqueId();
        initDevice(entry.getData());
    }

    /**
     * 网关子设备构造：无自身 entry，复用网关 entry 作 1:N back-ref。
     * <p>uniqueId 由集成从子设备硬件读取（≠ 网关 entry 的 uniqueId）；id 仍由 core 铸造 UUID，
     * 经 DeviceRegistry.getOrCreate 用持久化值覆盖以跨重启稳定。
     *
     * @param gatewayEntry 创建此子设备的网关 ConfigEntry（getEntry().getEntryId() 即网关 entryId）
     * @param uniqueId     子设备硬件原生 uniqueId
     * @param config       子设备运行时配置（由网关组装）
     */
    public DeviceBase(ConfigEntry gatewayEntry, String uniqueId, Map<String, Object> config) {
        this.log = LogFactory.getLogger(getClass());
        this.objectId = OBJECT_ID_GENERATOR.getAndIncrement();
        this.entry = gatewayEntry;
        this.config = config;
        this.id = java.util.UUID.randomUUID().toString();
        this.uniqueId = uniqueId;
        initDevice(config);
    }

    /**
     * 从 config Map 构建设备（旧式，已废弃）。
     * <p>新代码用 {@link #DeviceBase(ConfigEntry)}（entry-backed）或
     * {@link #DeviceBase(ConfigEntry, String, Map)}（网关子设备）。00-core Task 11 删除此构造。
     *
     * @param config 设备配置
     * @deprecated 使用 {@link #DeviceBase(ConfigEntry)} 或网关构造器替代
     */
    @Deprecated
    public DeviceBase(Map<String, Object> config) {
        this.log = LogFactory.getLogger(getClass());
        this.objectId = OBJECT_ID_GENERATOR.getAndIncrement();
        this.config = config;
        this.entry = new ConfigEntry(); // create empty config entry temporary
        this.id = java.util.UUID.randomUUID().toString();
        this.uniqueId = null;
        initDevice(config);
    }

    @SuppressWarnings("unchecked")
    private void initDevice(Map<String, Object> config) {
        this.name = (String) config.get("name");

        // sn is optional , if config not has sn set sn = null
        this.deviceClass = DeviceClasses.getEnum((String) config.getOrDefault("class", null));
        this.deviceStatus = DeviceStatus.UNKNOWN;
        this.abilities = new ArrayList<>();
        List<String> abilities = (List<String> ) config.getOrDefault("abilities", null);
        if(abilities != null){
            for (String ability : abilities) {
                this.abilities.add(DeviceAbility.getEnum(ability));
            }
        }

        this.sn = (String) config.getOrDefault("sn", null);
        this.vendor = (String) config.getOrDefault("vendor", null);
        this.model = (String) config.getOrDefault("model", null);

        this.attrs = new HashMap<>();
    }

    /**
     * 注入 core 并立即解析稳定 deviceId。
     *
     * <p>稳定 id 解析前置于 init/value 物化：load 是 device 拿到 core（从而能查 registry.matchIndex）的第一刻，
     * 此处 {@link DeviceRegistry#resolveStableId} 解析后，后续 createDeviceFromEntry 里的 init/updateValue/buildState
     * 物化的 AttrState 必带稳定 id——从根上消除"setId 改写 device.id 后 publicState flush 陈旧 midState
     * （带构造临时 UUID）→ 消费侧 registry 反查 null → realdata.type=null"。契约：各集成 createDeviceFromEntry
     * 内须 device.load(core) 早于 device.init()。
     *
     * <p>core 可能为测试用 null（未 setInstance 的 EcatCore.getInstance()）或 mock（getDeviceRegistry() 返 null）→ 跳过；
     * 生产 EcatCore 的 registry 是 final 字段永不为 null，真实路径必解析。详见 docs/2026-08-01-device-id-stable-before-state-design.md。
     */
    public void load(EcatCore core) {
        this.core = core;
        if (core == null) return;   // 测试用 null core（未 setInstance）→ 无 registry 可解析，跳过
        DeviceRegistry registry = core.getDeviceRegistry();
        if (registry != null) {
            registry.resolveStableId(this);
        }
    }

    /**
     * 设备主键 id（core 铸造的稳定 UUID）。全局唯一、跨重启稳定（DeviceRegistry.resolveStableId 用持久化值覆盖，
     * 在 load 时即解析，先于 init 物化任何 AttrState）。注册表 key、事件载荷、历史 FK、数据/逻辑关联均用此。
     * <p>LogicDevice 与物理设备同机制（构造铸造 UUID，resolveStableId 覆盖为持久化稳定值），无特例。
     *
     * @return 设备主键 UUID（构造铸造，可能已被 getOrCreate 覆盖为持久化值）
     */
    public String getId(){
        return id;
    }

    /**
     * 设备硬件锚点 uniqueId（coordinate 内唯一）。仅用于物理设备匹配/重复发现去重，不进业务/事件。
     * entry-backed 取自 entry.getUniqueId()；网关子设备取自构造入参。
     *
     * @return 硬件 uniqueId
     */
    public String getUniqueId(){
        return uniqueId;
    }

    /**
     * 包级私有 id setter：仅 com.ecat.core.Device 包（DeviceRegistry.getOrCreate）可调，
     * 用于把构造铸造的默认 UUID 覆盖为持久化的稳定 id，保证跨重启一致。外部 jar/集成无法改 id。
     */
    void setId(String id) {
        this.id = id;
    }

    /**
     * 获取设备的定时任务执行器
     * 
     */
    public ScheduledExecutorService getScheduledExecutor() {
        return this.core.getTaskManager().getExecutorService();
    }

    /**
     * 设置设备的配置信息，完成属性与设备的绑定
     * 
     * @param attr 需要设置的属性
     * 
     */
    public boolean setAttribute(AttributeBase<?> attr) {
        if (attr == null) {
            return false;
        }
        attr.setDevice(this); // 绑定属性与设备的关系以及使用device所在集成的i18n资源
        attrs.put(attr.getAttributeID(), attr);
        // 00-core（D9）：state 恢复已从 setAttribute 解耦——setAttribute 只注册。
        // 恢复由 restorePersistedState() 在 addDevice（getOrCreate 解析稳定 id）之后批量执行。
        // 原因：setAttribute 普遍在 init()（addDevice 之前）被调用，若此时 restore 会用未解析的构造期 id。
        return true;
    }

    /**
     * 00-core（D9）：批量恢复本设备全部 persistable 属性的持久化状态。
     * <p>由 {@code IntegrationDeviceBase.createEntry} 在 addDevice（getOrCreate 解析稳定 deviceId）之后、
     * start() 之前调用——确保用稳定 id 读 state DB，避免在 setAttribute（init 期、id 未解析）恢复。
     */
    public void restorePersistedState() {
        if (core == null || core.getStateManager() == null || attrs == null) {
            return;
        }
        for (AttributeBase<?> attr : attrs.values()) {
            if (attr.isPersistable()) {
                core.getStateManager().restoreAttributeState(this, attr);
            }
        }
    }

    /**
     * 设备生命周期阶段（READY 门禁的状态机）。初始 {@link DevicePhase#CONSTRUCTED}。
     *
     * <p>{@link AttributeBase#publicState()} 在 {@code phase < READY} 时抛 {@link IllegalStateException}
     * （硬门禁，替代原 boolean ready 的软挂起）。phase 写入唯一公开入口是 {@link #markReady()}（final）。
     * load/init/restore/start 等可被集成 override 的方法**不**推进 phase——把推进放进它们会随 override 漏推进
     * 而失效（load 今天被 ~48 个集成 override）。中间态（LOADED..STARTED）的接线留给 final 模板迁移，
     * 故当前仅 CONSTRUCTED→READY 经 markReady；publish 门禁只依赖 READY 边界，独立成立。详见 {@link DevicePhase}。
     *
     * <p>取值（诊断/状态机用）走 {@link #getPhase()}；判断设备就绪走 {@link #isReady()}，勿用 phase 直比。
     */
    @Getter
    private DevicePhase phase = DevicePhase.CONSTRUCTED;

    /**
     * 设备是否已就绪（phase &gt;= READY，即 markReady 已调）。
     *
     * <p>语义糖：等价 {@code getPhase().compareTo(DevicePhase.READY) >= 0}。供 {@link AttributeBase#publicState()}
     * 门禁与既有调用方使用；对 mock 设备可直接 stub 本方法。
     */
    public boolean isReady() {
        return phase.compareTo(DevicePhase.READY) >= 0;
    }

    /**
     * 严格推进到 READY：当前 phase 必须 &lt; READY（尚未就绪、未终态），否则抛 {@link IllegalStateException}。
     * 挡两类错：重复 markReady（已 READY/STARTED）、终态后误就绪（DISABLED/REMOVED）。严格模式不静默兜底。
     */
    private void transitionToReady() {
        if (this.phase.compareTo(DevicePhase.READY) >= 0) {
            throw new IllegalStateException(
                "设备生命周期非法迁移：当前 phase=" + this.phase + " 已就绪或已终态，不可重复 markReady"
                + "（deviceId=" + getId() + "）");
        }
        this.phase = DevicePhase.READY;
    }

    /**
     * 标记设备就绪：推进 phase + 排空预 ready 挂起发布 + 子类就绪期回调。
     *
     * <p>final——禁止集成 override 抢先就绪（phase=READY 唯一写入点）。封装三步，调用方只调一次：
     * <ol>
     *   <li>{@link #transitionToReady()}——phase → READY，publish 门禁放开；</li>
     *   <li>{@link #flushPendingPublishes()}——排空预 ready 期被门禁挂起的源属性 midState（因）；</li>
     *   <li>{@link #onReady()}——子类就绪期计算（果）：aggregate 等"需 device 就绪才能算+发"的派生初值
     *       在此统一算并发布。因先于果——源属性已在 ② 提交，aggregate 读到的是已提交因果态。</li>
     * </ol>
     * 须在 {@link #restorePersistedState()} 之后调用（物理 finalizeNewDevice / 逻辑 finalizeLogicDevice，
     * 均如此编排），使 flush 发出"最终态"（持久化值优先，否则 config 派生值），单次稳定 id 首发。
     */
    public final void markReady() {
        transitionToReady();
        flushPendingPublishes();
        onReady();
    }

    /**
     * 设备就绪期回调：phase 已 READY、预 ready 挂起已排空后触发，供子类做就绪期计算。
     *
     * <p>典型用途——逻辑设备的 aggregate 属性（alarm_status/running_status 等）依赖源数据属性，
     * 其初始值计算（{@code setupAfterDeviceAttrsCreated → updateBindAttrValue}）会调 publicState，
     * 必须在 device 就绪后执行才能过 publish 硬门禁；故从 init 期挪到本回调。物理设备默认不覆写
     * （初值在 start() 设，不依赖此钩子）。默认 no-op。
     */
    protected void onReady() {
    }

    /**
     * flush init 期被 ready 门禁挂起的属性发布：遍历 getAttrs 逐属性 publicState。
     *
     * <p>有在途变更（isValueUpdated）的才真发（用稳定 id）；无变更的 publicState 早 return。
     * 由 {@link #markReady()} 内部调，集成不直接调。
     */
    public void flushPendingPublishes() {
        if (attrs == null) {
            return;
        }
        for (AttributeBase<?> attr : attrs.values()) {
            try {
                attr.publicState();
            } catch (Exception e) {
                log.error("Failed to flush pending state for attribute {} of device {}",
                    attr.getAttributeID(), getId(), e);
            }
        }
    }

    public Map<String, AttributeBase<?>> getAttrs() {
        return attrs;
    }

    /**
     * 更新设备属性状态，提交给bus
     * 按需更新，只有属性值发生变化时才更新
     */
    public boolean publicAttrsState() {
        boolean allOk = true;
        for (AttributeBase<?> attribute : attrs.values()) {
            // 不吞异常：publicState 抛的就绪门禁 IllegalStateException = 设备未 READY 即 publish 的设计缺陷，
            // 直接冒泡让运行时暴露，绝不静默 log+return（吞异常会掩盖设计问题、拖死后续维护者）。
            // publicState 内部的落盘/总线发布失败由其自身处理（落盘失败抛出、发布失败返回 false 可重试），此处仅聚合结果。
            if (!attribute.publicState()) {
                allOk = false;
            }
        }
        return allOk;
    }

    /**
     * 接收设备的原始数据，用于integration统一收到数据后向device分发处理
     *
     * @param binaryArray 原始数据
     *
     */
    public void receiveRawData(byte[] binaryArray) {
        throw new UnsupportedOperationException("Not implemented");
    }

    /**
     * 获取设备类型名称，用于国际化分组
     * 默认实现基于类名自动生成，子类可以覆盖以提供自定义名称
     * 例如：
     * WeatherSensor -> weather_sensor
     * CODevice -> codevice
     * RACC2Device -> racc2device
     * Air5030iDevice -> air5030i_device
     *
     * @return 设备类型名称，小写格式
     */
    public String getTypeName() {
        String className = getClass().getSimpleName();
        // 将驼峰命名转换为下划线分隔的小写名称
        return className.replaceAll("([a-z])([A-Z]+)", "$1_$2").toLowerCase();
    }

    /**
     * 获取设备的国际化前缀路径
     * 用于按设备分组国际化资源
     *
     * @return I18nKeyPath 设备分组路径前缀，格式为 "devices.{deviceClassNameLowerCase}"
     */
    public I18nKeyPath getI18nPrefix() {
        String typeName = getTypeName();
        if (typeName != null && !typeName.isEmpty()) {
            return new I18nKeyPath("devices." + typeName + ".", "");
        } else {
            return null;
        }
    }

}
